export const APP = {
  REQUIRED_FIELD: 'Поле обязательно для заполнения',
  VALID_EMAIL: 'Необходимо ввести валидный E-mail',
  ERROR_PHONE_NUMBER: 'Неправильный номер телефона',
  PASSWORD_MIN_LIMIT: 'Пароль должен содержать не менее 4 символов',
  PUBLISH: 'Опубликовать',
  REMOVE: 'Удалить',
  CHANGE: 'Изменить',
  EXIT: 'Выйти из аккаунта',
  MY_PROFILE: 'Мой профиль',
  ENTER_TO_SYSTEM: 'Войти в систему',
  ADD_USER: 'Добавить пользователя',
  ACTIVATED_USER: 'Активный',
  NOT_ACTIVATED_USER: 'Неактивный',
  FIRST_NAME: 'Имя',
  LAST_NAME: 'Фамилия',
  USERNAME: 'Логин',
  EMAIL: 'Электронная почта',
  PHONE: 'Телефон номер',
  PASSWORD: 'Пароль',
  STATUS: 'Статус',
  CANCEL: 'Отменить',
  SAVE: 'Сохранить',
  PHOTO: 'Фотография',
  REMOVE_PHOTO: 'Удалить фотографию',
  ENTER_FIRST_NAME: 'Введите имя',
  ENTER_LAST_NAME: 'Введите фамилию',
  ENTER_USERNAME: 'Введите логин',
  ENTER_EMAIL: 'Введите Электронную почту',
  ENTER_PHONE: 'Введите телефон номер',
  ENTER_PASSWORD: 'Введите пароль',
  ADMIN: 'Админ',
  ADD_FILE: 'Добавить файл',
  DATA_SUCCESS_SAVED: 'Данные успешно сохранены!',
  DATA_SUCCESS_CHANGED: 'Данные успешно изменены!',
  DATA_SUCCESS_REMOVED: 'Данный успешно удален!',
  DATA_FAILURE_SAVED: 'Данные не сохранены!',
  CHANGE_PASSWORD: 'Изменить пароль',
  OLD_PASSWORD: 'Текущий пароль',
  NEW_PASSWORD: 'Новый пароль',
  CONFIRM_PASSWORD: 'Подтвердите новый пароль',
  ENTER_OLD_PASSWORD: 'Введите текущий пароль',
  ENTER_NEW_PASSWORD: 'Введите новый пароль',
  REPEAT_PASSWORD: 'Повторите пароль',
  PASSWORD_MUST_MATCH: 'Пароль не совпадает',
  PASSWORD_CHANGED: 'Пароль успешно изменен',
  CHANGE_BANNER: 'Изменить баннер',
  TITLE: 'Название',
  LINK: 'Ссылка',
  ENTER_TITLE: 'Введите названию',
  ENTER_LINK: 'Введите ссылку',
  ERROR_LINK: 'URL-адрес должен быть действительным',
  TEXT: 'Текст',
  ADD_HISTORY: 'Добавить историю',
  ADD_PLAN: 'Добавить план',
  DATE_TIME: 'Дата время',
  ENTER_TEXT: 'Введите текст',
  FOR_MONTH: 'На месяц',
  FOR_YEAR: 'На год',
  PLAN: 'План',
  ADD_POPUP: 'Добавить поп-ап',
  VIDEO: 'Видео',
  VIDEO_URL: 'Видео URL'
}

